var price1 = 35;
var price2 = 10;
var totalPrice = price1 + price2;
// console.log(totalPrice);

var firstName = 'Jennie';
var lastName = 'Kim';
var fullName = firstName + lastName;
// console.log(fullName);
var firstName = 'Jennie';
var lastName = 'Kim';
var fullName = firstName +'x' +lastName;
// console.log(fullName);
var firstName = 'Jennie';
var lastName = 'Kim';
var fullName = firstName +'' +lastName;
// console.log(fullName);
var firstName = 'Jennie';
var lastName = 'Kim';
var fullName = firstName +' ' +lastName;
console.log(fullName);